#
# Autogenerated by Thrift Compiler (0.14.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:package_prefix=controller.thrift_api.
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class DevTarget_t(object):
    """
    Attributes:
     - dev_id
     - dev_pipe_id

    """


    def __init__(self, dev_id=None, dev_pipe_id=None,):
        self.dev_id = dev_id
        self.dev_pipe_id = dev_pipe_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.dev_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.dev_pipe_id = iprot.readI16()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DevTarget_t')
        if self.dev_id is not None:
            oprot.writeFieldBegin('dev_id', TType.I32, 1)
            oprot.writeI32(self.dev_id)
            oprot.writeFieldEnd()
        if self.dev_pipe_id is not None:
            oprot.writeFieldBegin('dev_pipe_id', TType.I16, 2)
            oprot.writeI16(self.dev_pipe_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.dev_id is None:
            raise TProtocolException(message='Required field dev_id is unset!')
        if self.dev_pipe_id is None:
            raise TProtocolException(message='Required field dev_pipe_id is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class DevParserTarget_t(object):
    """
    Attributes:
     - dev_id
     - gress_id
     - dev_pipe_id
     - parser_id

    """


    def __init__(self, dev_id=None, gress_id=None, dev_pipe_id=None, parser_id=None,):
        self.dev_id = dev_id
        self.gress_id = gress_id
        self.dev_pipe_id = dev_pipe_id
        self.parser_id = parser_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.dev_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.BYTE:
                    self.gress_id = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I16:
                    self.dev_pipe_id = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.BYTE:
                    self.parser_id = iprot.readByte()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('DevParserTarget_t')
        if self.dev_id is not None:
            oprot.writeFieldBegin('dev_id', TType.I32, 1)
            oprot.writeI32(self.dev_id)
            oprot.writeFieldEnd()
        if self.gress_id is not None:
            oprot.writeFieldBegin('gress_id', TType.BYTE, 2)
            oprot.writeByte(self.gress_id)
            oprot.writeFieldEnd()
        if self.dev_pipe_id is not None:
            oprot.writeFieldBegin('dev_pipe_id', TType.I16, 3)
            oprot.writeI16(self.dev_pipe_id)
            oprot.writeFieldEnd()
        if self.parser_id is not None:
            oprot.writeFieldBegin('parser_id', TType.BYTE, 4)
            oprot.writeByte(self.parser_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.dev_id is None:
            raise TProtocolException(message='Required field dev_id is unset!')
        if self.gress_id is None:
            raise TProtocolException(message='Required field gress_id is unset!')
        if self.dev_pipe_id is None:
            raise TProtocolException(message='Required field dev_pipe_id is unset!')
        if self.parser_id is None:
            raise TProtocolException(message='Required field parser_id is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(DevTarget_t)
DevTarget_t.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'dev_id', None, None, ),  # 1
    (2, TType.I16, 'dev_pipe_id', None, None, ),  # 2
)
all_structs.append(DevParserTarget_t)
DevParserTarget_t.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'dev_id', None, None, ),  # 1
    (2, TType.BYTE, 'gress_id', None, None, ),  # 2
    (3, TType.I16, 'dev_pipe_id', None, None, ),  # 3
    (4, TType.BYTE, 'parser_id', None, None, ),  # 4
)
fix_spec(all_structs)
del all_structs
