#ifndef C_CONTROLLER_TCP_H
#define C_CONTROLLER_TCP_H

#include "datastructures/structs.h"

/*
 * A table of TCP Flags and their state transitions
 * [direction][flag][old state] -> new state
 */
static tcp_state_t transitions[][NUM_FLAGS][NUM_STATES] = {
		{
				// Direction: ORIGINAL
				// State.NONE, State.SYN_SENT, State.SYN_RECV, State.ESTABLISHED, State.FIN_WAIT, State.CLOSE_WAIT, State.LAST_ACK, State.TIME_WAIT, State.CLOSE, State.SYN_SENT2
				{SYN_SENT, SYN_SENT,  IGNORE,  IGNORE,  IGNORE,  IGNORE,  IGNORE,  SYN_SENT, SYN_SENT, SYN_SENT2},
				{INVALID, INVALID,  SYN_RECV, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, SYN_RECV},
				{INVALID, INVALID, FIN_WAIT, FIN_WAIT, LAST_ACK, LAST_ACK, LAST_ACK, TIME_WAIT, CLOSE, INVALID},
				{ESTABLISHED, INVALID, ESTABLISHED, ESTABLISHED, CLOSE_WAIT, CLOSE_WAIT, TIME_WAIT, TIME_WAIT, CLOSE, INVALID},
				{INVALID, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE},
				{INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID},
				// copy from fin set to fin/ack set
				{INVALID, INVALID, FIN_WAIT, FIN_WAIT, LAST_ACK, LAST_ACK, LAST_ACK, TIME_WAIT, CLOSE, INVALID}
		},
		{
				// Direction: REPLY
				// State.NONE, State.SYN_SENT, State.SYN_RECV, State.ESTABLISHED, State.FIN_WAIT, State.CLOSE_WAIT, State.LAST_ACK, State.TIME_WAIT, State.CLOSE, State.SYN_SENT2
				{INVALID,  SYN_SENT2, INVALID, INVALID, INVALID, INVALID, INVALID, SYN_SENT, INVALID,  SYN_SENT2},
				{INVALID, SYN_RECV, IGNORE,   IGNORE,  IGNORE,  IGNORE,  IGNORE,  IGNORE,  IGNORE,  SYN_RECV},
				{INVALID, INVALID, FIN_WAIT, FIN_WAIT, LAST_ACK, LAST_ACK, LAST_ACK, TIME_WAIT, CLOSE, INVALID},
				{INVALID,     IGNORE,  SYN_RECV,    ESTABLISHED, CLOSE_WAIT, CLOSE_WAIT, TIME_WAIT, TIME_WAIT, CLOSE, IGNORE},
				{INVALID, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE, CLOSE},
				{INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID, INVALID},
				// copy from fin set to fin/ack set
				{INVALID, INVALID, FIN_WAIT, FIN_WAIT, LAST_ACK, LAST_ACK, LAST_ACK, TIME_WAIT, CLOSE, INVALID}
		}
};


#endif //C_CONTROLLER_TCP_H
